#!/bin/bash

export DOTDIR="$HOME/.config"
export ZDOTDIR="$DOTDIR/zsh"
export DOTENV="$DOTDIR/op/env.sh"

if [ -f "$DOTENV" ]; then
    source "$DOTENV"
fi
if [ ! -d "$ZDOTDIR" ]; then
    mkdir -p "$ZDOTDIR"
    touch "$ZDOTDIR/.zshrc"
fi
